### ISSUE TITLE
Add "Django manage.py anywhere"

### ISSUE THREAD

**Issue by timonweb** [rosarior/awesome-django#118]
A fresh project, but I hope you consider it useful: https://github.com/timonweb/Django-manage.py-anywhere

**Comment by rosarior** [comment]
I like the concept, but trying it gave a few errors:

```
  File "/usr/local/bin/manage.py", line 8
    while [[ "`pwd`" != '/' ]]; do
                              ^
SyntaxError: invalid syntax
```

and running by accident from the root directory locked up the terminal session.

Running inside the project folder with the virtualenv activated worked as expected.

I guess the Others section or a new Utilities section will be the best place to add it.

**Comment by rosarior** [comment]
Add to new "Utilities" section where we can add more non Django projects that help work with Django. 
REF: 14d9c0a2042fefb58f0fee2cc86c81419291c924
