### ISSUE TITLE
Image (logo) was broken (turns out it was a timeout)

### ISSUE THREAD

**Issue by jonashagstedt** [rosarior/awesome-django#121]
The https://raw.githubusercontent.com/rosarior/awesome-django/gh-pages/images/logo-small.png image is timing out sometimes.

Not a big issue of course, and other than that it all looks good

**Comment by rosarior** [comment]
The site is being hosted in github itself, must have been a temporary server hiccup. Will leave open for some 24-48 hours just in case.

**Comment by rosarior** [comment]
Hosting service appears to be up and running, closing for now.
