### ISSUE TITLE
A new section for django-analytical?

### ISSUE THREAD

**Issue by bittner** [rosarior/awesome-django#152]
I'd like to add [django-analytical](https://github.com/jcassee/django-analytical) to the list. However, I'm unsure where it fits in.

The project is about adding code snippets of various analytics services to templates in a clean way. So, it's about e-commerce, but it's not an e-commerce project as such (as I understand that section in the list).

Any suggestions?

**Comment by bittner** [comment]
@rosarior Roberto, what would you suggest?

**Comment by rosarior** [comment]
Hi @bittner I would prefer a whole new section for analytics integration. I can add the section but if you can add the section in the pull request I will merge it too, no problem.
