### ISSUE TITLE
Pull request rejection

### ISSUE THREAD

**Issue by djangoconcardiff** [rosarior/awesome-django#176]
Hi

great project!!  I have one observation and a suggestion.  I noticed you have rejected some pull requests to add some good django libraries and that the people submitting those pull requests are POCs (People of Colour).  As a suggestion I recommend adopting the Contributor Code of Conduct (<http://contributor-covenant.org>) to ensure everybody's contributions are accepted regarless of their sex, sexual orientation, skin color, religion, height, place of origin, etc, etc, etc.  As a white straight male and lead of this trending repository, your adoption of this Code of Conduct will send a loud and clear message that inclusion is a primary objective of the Django community and of the software development community in general.  D.

**Comment by rosarior** [comment]
The pull request was rejected not the person. Of the people who did not had their patches accepted at least one submitted another pull request and was accepted or are contributors in my other repositories, disproving your basic premise. 

There is no need for a code of conduct, there hasn't been a conduct related incident with the repository and nothing about a contributor comes into play when rejecting or accepting a patch (as proved above). An explanation is provided when a patch is rejected, and some have been left open to re-asses in a future time.

I'm not white and please don't make any other assumptions about me, they hold no relevance to the matter at hand.

I already work on several projects that hold inclusion as one of their primary goals.

I'm closing this issue based on the explanations given.

**Comment by djangoconcardiff** [comment]
You seem to have taken personal issue with well the issue :)   I opened this issue not to attack you or your decisions,but to help improve a part of the project in which it seemed lacking.  Most projects on Github have adopted the Contributor Covenant or a variant of it.   It is a very straight forward document that protects all parties,I don't understand your negative attitude towards that philosophy.   You may not be "white" <in your profile picture you sure seem white :) > but you are not a woman or a trans-gendered person so you can't possibly understand what they go through  (harassment,exclusion,threats) and why a code of conduct is necessary.  Even the Django Software Foundation has adopted one to protect it's future,for me it's very obvious Django related projects would naturally follow suite and adopt the same if not similar Code of Conducts.   I urge you to reconsider for the good and future of this project :)    Thank you

**Comment by rosarior** [comment]
1- You opened an issue to raise concern about the relationship of a contributor's race and the rejection of their patches.
2- Only I can accept or reject patches in this repository.

You made it clear who this was about.

Apart from this issue, we've had no conduct problems, so no need for a code of conduct.

I'm very certain of my race: I'm Latino, Puertorican, a Mestizo from a Castiza mother and a Mulato father. There are many more races than just black and white (https://en.wikipedia.org/wiki/Miscegenation).

Yes, I'm not a woman or a transgendered individual and I don't intend to even try to understand what they have to put up with, never said that. But you assume women and transgendered individual are the only targets of harassment, exclusion and threats.

https://feelsandreals.wordpress.com/2015/01/31/igda-puerto-rico-closes-too-suddenly/
https://mail.python.org/pipermail/python-cuba/2015-July/000106.html
https://twitter.com/siloraptor/status/624257540948393988

English is not my first language and I hope I'm mistaken but your last line
"I urge you to reconsider for the good and future of this project :) "
sounded like a threat, please clarify.

**Comment by djangoconcardiff** [comment]
I really have no idea why you are responding the way you are!   Really!!   Code of Conducts are not JUST about conduct,they cover all the spectrum of behaviours expected from civilized human beings that are more and more absend in the software industry.  You are evading the topic at hand and I can only wonder why,why deny equal opportunity for all to join and contribute to your project Roberto?

That you have not "seen" harassment doesn't mean it is not happening all around us.   And turning a blind eye makes it worst.  I was not threaning you,but your reaction is a projection of your feelings and now I feel threated by you.  Reading the links you posted I only have one thing to say to you:reevaluate your actions,you are becoming a toxic individual who is harming the Python and Django communities and haven't even realized it yet.  You are a member of the Django Software Foundation and are supposed to be setting the example.   I will be forwarding the content of this issue to the Chair to evaluate your continued presence in the DSF.  best regards.

**Comment by rosarior** [comment]
I have reported this issue to Github. Future issues about this or related topics will be closed and locked without reply.
