### ISSUE TITLE
One Month Django no longer available?

### ISSUE THREAD

**Issue by jangondol** [rosarior/awesome-django#231]
It seems that [One Month Django](https://onemonth.com/) is no longer available. [The website](http://learn.onemonth.com/why-you-should-learn-python-as-your-next-or-first-programming-language) says: "**Why did you change the course up and re-launch it?** -> Because our initial Python course focused on Django and building web apps but not really Python and a lot of the stuff you can do with Python. // We wanted to make the course better and we’re confident that we’ve developed a really good curriculum that works and will show off projects that students are really excited to complete."

[The Syllabus](https://onemonth.com/courses/python/preview) of the re-launched course no longer mentions Django (only Flask). If the course is indeed no longer available, consider removing the link.

**Comment by rachmadaniHaryono** [comment]
hi, i create a fork of this project and add fix for issue you mentioned

https://github.com/rachmadaniHaryono/awesome-django/commit/649621f88ec4ef8c72fe4baaf75e67dcedcded02

rather than delete the entry, i just add notice that the course is no longer include django
