### ISSUE TITLE
Is this project in active maintenance?

### ISSUE THREAD

**Issue by ravigadila** [rosarior/awesome-django#234]
I didn't receive any response for my pull request
[#228](https://github.com/rosarior/awesome-django/pull/228)
[#229](https://github.com/rosarior/awesome-django/pull/229)
[#233](https://github.com/rosarior/awesome-django/pull/233)

**Comment by bittner** [comment]
I suggest you move your PRs to GitLab. https://gitlab.com/rosarior/awesome-django

**Comment by rachmadaniHaryono** [comment]
@ravigadila I have made the fork and already add your pr. 

This fork fix url link and will try synchronize rosarior repo on github also add package from django package.

**Comment by rachmadaniHaryono** [comment]
@ravigadila #233 https://github.com/rachmadaniHaryono/awesome-django/commit/2e6d3afcde7f2c87741edd776367ec10cb42b97b
