### ISSUE TITLE
Add opps project and widgy

### ISSUE THREAD

**Issue by auvipy** [rosarior/awesome-django#98]
https://github.com/opps/opps

https://wid.gy/

**Comment by rosarior** [comment]
It's on my queue to test and add, thanks for the suggestion.

**Comment by rachmadaniHaryono** [comment]
hi, i create a fork of this project and add fix for issue you mentioned

https://github.com/rachmadaniHaryono/awesome-django/commit/686958261415c6ab4f561999feeef77d13dc686a
